fit:
  data:
    class_path: autoregressive.datasets.MNISTDataModule
    init_args:
      binarize: true
      apply_peano_map: false
      batch_size: 64
      num_workers: 0
      digit_conditioning: true
  seed_everything: null
  trainer:
    logger: true
    checkpoint_callback: null
    enable_checkpointing: true
    callbacks: null
    default_root_dir: null
    gradient_clip_val: null
    gradient_clip_algorithm: null
    process_position: 0
    num_nodes: 1
    num_processes: 1
    devices: null
    gpus: 1
    auto_select_gpus: false
    tpu_cores: null
    ipus: null
    log_gpu_memory: null
    progress_bar_refresh_rate: null
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    accumulate_grad_batches: null
    max_epochs: 30
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    flush_logs_every_n_steps: null
    log_every_n_steps: 25
    accelerator: null
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    weights_summary: top
    weights_save_path: null
    num_sanity_val_steps: 2
    resume_from_checkpoint: null
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    prepare_data_per_node: null
    plugins: null
    amp_backend: native
    amp_level: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
    terminate_on_nan: null
  model:
    wave_dilations:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    wave_kernel_size: 2
    residual_channels: 32
    dilation_channels: 32
    skip_channels: 1024
    cond_channels: 10
    head_channels: 512
    input_kernel_size: 3
    conv_bias: false
    train_opts:
      skip_partial: false
      lr: 0.002
      sched_patience: 500
      train_ro_horizon: 1
      train_ro_num_origins: null
      train_ro_loss_lambda: 1.0
      val_ro_horizon: 1
      val_ro_num_origins: null
  ckpt_path: null
