language: python
python:
- 3.9
cache:
  pip: true
install:
- pip install git+https://github.com/cheind/autoregressive.git#egg=autoregressive[dev]
script:
- pytest
notifications:
  email:
    if: branch = main
    on_success: never
    on_failure: never