seed_everything: null
trainer:
  logger: true
  checkpoint_callback: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: 0.0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 30
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 25
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  wave_dilations:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  wave_kernel_size: 2
  wave_channels: 32
  cond_channels: 21
  input_kernel_size: 7
  train_opts:
    skip_partial: false
    lr: 0.01
    sched_patience: 50
    train_ro_horizon: 8
    train_ro_num_origins: 16
    val_ro_horizon: 8
    val_ro_num_origins: 8
data:
  class_path: autoregressive.datasets.FSeriesDataModule
  init_args:
    quantization_levels: 127
    batch_size: 64
    num_workers: 0
    period_conditioning: true
    train_params:
      num_curves: 8192
      num_tsamples: 2048
      dt: 0.02
      fterm_range:
      - 3
      - 3
      tstart_range: 0.0
      period_range:
      - 3.0
      - 20.0
      bias_range: 0.0
      coeff_range:
      - -1.0
      - 1.0
      phase_range:
      - -3.141592653589793
      - 3.141592653589793
      lineartrend_range: 0.0
      smoothness: 0.75
      seed: null
      noise_scale: 0.0
    val_params: null
