data:
  class_path: autoregressive.datasets.FSeriesDataModule
  init_args:
    quantization_levels: 127
    batch_size: 16
    num_workers: 0
    train_params:
      num_curves: 8192
      num_tsamples: 2048
      dt: 0.02
      fterm_range:
      - 3
      - 3
      tstart_range: 0.0
      period_range:
      - 5
      - 10
      bias_range: 0.0
      coeff_range:
      - -1.0
      - 1.0
      phase_range:
      - -3.141592653589793
      - 3.141592653589793
      lineartrend_range: 0.0
      smoothness: 0.75
      noise_scale: 0.0
    period_conditioning: true
